"""make salary nullable

Revision ID: dd3b1fc9415f
Revises: b9576205c1c8
Create Date: 2025-10-09 15:21:53.972767

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dd3b1fc9415f"
down_revision = "b9576205c1c8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jobs",
        "salary_from",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=True,
        existing_comment="Зарплата от",
    )
    op.alter_column(
        "jobs",
        "salary_to",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=True,
        existing_comment="Зарплата до",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jobs",
        "salary_to",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=False,
        existing_comment="Зарплата до",
    )
    op.alter_column(
        "jobs",
        "salary_from",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=False,
        existing_comment="Зарплата от",
    )
    # ### end Alembic commands ###
