"""add unique constraint to user_job_response

Revision ID: 7415f9358430
Revises: dd3b1fc9415f
Create Date: 2025-10-09 15:24:55.209041

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7415f9358430"
down_revision = "dd3b1fc9415f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_user_job_response", "responses", ["user_id", "job_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_job_response", "responses", type_="unique")
    # ### end Alembic commands ###
